### ISSUE TITLE
Crossfire regions compatibility

### ISSUE THREAD

**Issue by rruipinheiro** [ZettaStudios/crossfire-dotnet#12]
Hi,

Is this compatible with recents versions of crossfire europe/na?

**Comment by guinhx** [comment]
This repository has been discontinued, but answering your question, no, this server at the time I developed it only supported the latest version 2.0 of CrossFire NA/West.
I'm developing another server for the game following the game's package structure to the letter and other points as well but it won't be open to the public like this one.

**Comment by rruipinheiro** [comment]
Thanks for the answer

**Comment by progratient** [comment]
> This repository has been discontinued, but answering your question, no, this server at the time I developed it only supported the latest version 2.0 of CrossFire NA/West. I'm developing another server for the game following the game's package structure to the letter and other points as well but it won't be open to the public like this one.

How can we find the full source code of CF 1.0 (server + client)?
